apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello-world
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  successfulJobsHistoryLimit : 5
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: hello
            image: quay.io/prometheus/busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello world!
          restartPolicy: Never